---
permalink: windows/reference_the_smosmsapprofile_update_command.html 
sidebar: sidebar 
keywords: run, profile, update, command, information, existing, smo 
summary: 您可以執行設定檔更新命令來更新現有設定檔的資訊。 
---
= 使用者可執行「SMO設定檔更新」命令
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以執行設定檔更新命令來更新現有設定檔的資訊。



== 語法

[listing]
----

        smo profile update
-profile profile
\[-new-profile new_profile_name\]
\[-profile-password profile_password\]
[-database
-dbname db_dbname
-host db_host
\[-sid db_sid\]
[-login
\[-username db_username -password db_password -port db_port\]
 ]
[\{-rman  \{-controlfile \| \{\{-login
-username  rman_username
-password  rman_password \}
\[-tnsname  tnsname\]\}\}\} \|
-remove-rman\]


[-retain
\[-hourly \[-count n\] \[-duration m\]\]
\[-daily \[-count n\] \[-duration m\]]
\[-weekly \[-count n\] \[-duration m\]]
\[-monthly \[-count n\] \[-duration m\]]]]
-comment comment
-snapname-patternpattern
[]
[-summary-notification]
[-notification
\[-success
-email email_address1,email_address2
-subject subject_pattern\]
\[-failure
-email email_address1,email_address2
-subject subject_pattern]
[-separate-archivelog-backups
-retain-archivelog-backups
-hours  hours |
-days days |
-weeks weeks |
-months months
[]
[-include-with-online-backups \| -no-include-with-online-backups]]
[-dump]
\[-quiet \| -verbose\]
----


== 參數

* *設定檔設定檔*
+
指定設定檔的名稱。此名稱最長可達30個字元、且在主機內必須是唯一的。

* *設定檔密碼設定檔密碼*
+
指定設定檔的密碼。

* 新設定檔new_profile_name*
+
指定可為設定檔提供的新名稱。

* *資料庫*
+
指定設定檔所描述之資料庫的詳細資料。這是要備份、還原的資料庫、依此類推。

* *-dbname db_dbname*
+
指定設定檔所描述的資料庫名稱。您可以使用全域名稱或系統識別碼。

* *主機db_host*
+
指定執行資料庫的主機電腦名稱或IP位址。

* -SID db_SID*
+
指定設定檔所描述之資料庫的系統識別碼。根據預設SnapManager 、系統識別碼會使用資料庫名稱。如果系統識別碼與資料庫名稱不同、您必須使用-sID選項來指定。

* *登入*
+
指定儲存庫登入詳細資料。

* *使用者名稱repo_username*
+
指定存取儲存庫資料庫所需的使用者名稱。

* *連接埠repo_port*
+
指定存取儲存庫資料庫所需的TCP連接埠號碼。

* *資料庫*
+
指定設定檔所描述之資料庫的詳細資料。這是要備份、還原或複製的資料庫。

* *-dbname db_dbname*
+
指定設定檔所描述的資料庫名稱。您可以使用全域名稱或系統識別碼。

* *主機db_host*
+
指定執行資料庫的主機電腦名稱或IP位址。

* *登入*
+
指定資料庫登入詳細資料。

* *使用者名稱db_username*
+
指定存取設定檔所描述之資料庫所需的使用者名稱。

* *密碼db_password*
+
指定存取設定檔所描述之資料庫所需的密碼。

* *連接埠db_port*
+
指定存取設定檔所描述之資料庫所需的TCP連接埠號碼。

* *-RMAN *
+
指定SnapManager 使用Oracle Recovery Manager（RMAN）來分類備份的詳細資料。

* *控制檔*
+
指定目標資料庫控制檔、而非目錄做為RMAN儲存庫。

* *登入*
+
指定RMAN登入詳細資料。

* *密碼RMAN密碼*
+
指定用於登入RMAN目錄的密碼。

* *使用者名稱RMAN_USERNAME*
+
指定用於登入RMAN目錄的使用者名稱。

* -tnssname tnssname*
+
指定tnsname連線名稱（定義於tssname.ora檔案）。

* *移除RMAN *
+
指定移除設定檔上的RMAN。

* *保留[-每小時[-countn][-持續時間m][-每日[-countn][-持續時間m]][-每週[-countn][-duration m]]][-每月[-countn][-持續時間m]]]*
+
指定備份的保留類別（每小時、每日、每週、每月）。

+
對於每個保留類別、都可以指定保留計數或保留期間、或兩者都指定。持續時間以課程單位為單位（例如小時或日）。例如、如果使用者僅指定每日備份的保留時間為7、SnapManager 則不會限制設定檔的每日備份次數（因為保留次數為0）、SnapManager 但無法自動刪除7天前建立的每日備份。

* *留言留言*
+
指定設定檔的註解。

* *快照名稱模式*
+
指定Snapshot複本的命名模式。您也可以在所有Snapshot複本名稱中加入自訂文字、例如用於高可用度作業的HAOPS。您可以在建立設定檔或建立設定檔之後、變更Snapshot複本命名模式。更新的模式僅適用於尚未發生的Snapshot複本。現有的Snapshot複本會保留先前的Snapname模式。您可以在模式文字中使用多個變數。

* *摘要通知*
+
指定已啟用現有設定檔的摘要電子郵件通知。

* *通知[-s字 成功電子郵件、email_address1、電子郵件地址2 -主題Subject模式]*
+
啟用現有設定檔的電子郵件通知、以便在SnapManager 執行完動作後、收件者能收到電子郵件。您必須輸入要傳送電子郵件警示的單一電子郵件地址或多個電子郵件地址、以及現有設定檔的電子郵件主旨模式。

+
您可以在更新設定檔時變更主旨文字、或加入自訂主旨文字。更新的主旨僅適用於未傳送的電子郵件。您可以針對電子郵件主旨使用多個變數。

* *通知[-失敗-電子郵件email_address1、電子郵件地址2 -主旨Subject模式]*
+
啟用現有設定檔的電子郵件通知、以便接收者在SnapManager 無法執行此操作時收到電子郵件。您必須輸入要傳送電子郵件警示的單一電子郵件地址或多個電子郵件地址、以及現有設定檔的電子郵件主旨模式。

+
您可以在更新設定檔時變更主旨文字、或加入自訂主旨文字。更新的主旨僅適用於未傳送的電子郵件。您可以針對電子郵件主旨使用多個變數。

* *獨立的歸檔儲存設備備份*
+
將歸檔記錄備份與資料檔案備份分開。這是可在建立設定檔時提供的選用參數。使用此選項分隔備份之後、您可以建立純資料檔案備份或僅歸檔記錄備份。

* *保留歸檔日誌備份-小時數|-日天數|-週數週|-月數*
+
指定根據歸檔記錄保留期間（每小時、每日、每週、每月）來保留歸檔記錄備份。

* 包括線上備份|-no include-with online備份*
+
指定在線上資料庫備份時隨附歸檔記錄備份。

+
指定不會隨線上資料庫備份一起提供歸檔記錄備份。

* *傾印*
+
指定在成功建立設定檔之後收集傾印檔。

* *-無聲*
+
僅在主控台顯示錯誤訊息。預設為顯示錯誤和警告訊息。

* *-詳細*
+
在主控台顯示錯誤、警告和資訊訊息。





== 範例

下列範例會變更設定檔所述資料庫的登入資訊、並針對此設定檔設定電子郵件通知：

[listing]
----
smo profile update -profile SALES1 -database -dbname SALESDB
 -sid SALESDB -login -username admin2 -password d4jPe7bw -port 1521
-host server1 -profile-notification -success -e-mail Preston.Davis@org.com -subject success
Operation Id [8abc01ec0e78ec33010e78ec3b410001] succeeded.
----
*相關資訊*

xref:task_changing_profile_passwords.adoc[變更設定檔密碼]

xref:concept_how_snapmanager_retains_backups_on_the_local_storage.adoc[如何在本機儲存設備上保留備份SnapManager]
