---
permalink: windows/task_configuring_e_mail_notification_for_an_existing_profile.html 
sidebar: sidebar 
keywords: updating, profile, configure, receive, email, notification, completion, database, operation, configuring, existing 
summary: 當您更新設定檔時、可以設定在資料庫作業完成時接收電子郵件通知。 
---
= 設定現有設定檔的電子郵件通知
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
當您更新設定檔時、可以設定在資料庫作業完成時接收電子郵件通知。

* 您必須設定傳送警示的電子郵件地址。
* 您必須輸入要傳送警示的單一電子郵件地址或多個電子郵件地址。
+
您可以針對多個位址使用以逗號分隔的清單。您必須確保在逗號和下一個電子郵件地址之間沒有空格。您也可以選擇新增主旨至電子郵件。

+

NOTE: 您必須確保在雙引號內輸入多個電子郵件地址集。

+
.. 輸入下列命令：smo profile update -profileprofile [-profile-passworthprofile_password][-database-dbnamedb_dbname-host db_host [-iddb_sid][-logoaddressedb_username-password_port db_port][{-rMAN {-controlfile |{-login-usernam_deparam_deletailen-tam_depam_depameden_noteedun][-peepyour_noteepyour_noteep][-peedenam_deleepyagm_sam_deepam_deepam_delam_deepam_deepam_dep][-name_noteepam_del][-name_noteepam_delam_delam_noteeparam_deleepyagm_sam_deepam_depam_delam_noteepamed][-name_noteepyeepyeepamed][-name[-name_noteep/cam_del][-name_
+
您可以使用「成功」選項來接收通知、只有在資料庫作業成功時才會收到通知、而失敗選項則只會收到失敗資料庫作業的通知。




