---
permalink: windows/task_updating_target_database_hostname_associated_with_a_profile.html 
sidebar: sidebar 
keywords: snapmanager, oracle, ability, update, host, name, target, database, profile, updating, profile 
summary: 適用於Oracle的零組件（3.2或更新版本）可在支援的功能中更新目標資料庫的主機名稱。SnapManager SnapManager 
---
= 更新與設定檔相關聯的目標資料庫主機名稱
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
適用於Oracle的零組件（3.2或更新版本）可在支援的功能中更新目標資料庫的主機名稱。SnapManager SnapManager

* 本機使用者的主目錄必須知道設定檔對儲存庫的對應。
* 必須關閉圖形化使用者介面（GUI）工作階段。SnapManager


您只能使用CLI、以新的主機名稱更新設定檔。

*不支援在設定檔*中變更目標資料庫主機名稱的情況

下列情況不支援變更設定檔中的目標資料庫主機名稱：

* 使用SnapManager Isname GUI變更目標資料庫主機名稱
* 更新設定檔的目標資料庫主機名稱後、將儲存庫資料庫復原
* 執行單一命令來更新新目標資料庫主機名稱的多個設定檔
* 執行SnapManager 任何功能不全的作業時、請變更目標資料庫主機名稱



NOTE: 在設定檔中更新目標資料庫主機名稱之後、只會變更目標資料庫主機名稱。設定檔上設定的所有其他組態參數都會保留。

更新目標資料庫主機名稱之後、如果新主機中沒有可用的實體複本或掛載備份、則無法刪除或卸載備份。在這種情況SnapManager 下、從新主機執行支援功能會導致故障、以及舊主機中的過時項目。若要執行SnapManager 還原作業、您必須使用設定檔更新來還原至較早的主機名稱。

. 輸入下列命令：smo profile update -profileprofile [-profile-password-countprofile_password][-database-dbnamedb_dbname-hostdb_host [-addressiddb_sid][-login-useraddressedb_username-passworddb_password-portdb_port][{-rMAN {-controlfile |｛-login_dure-deparamed-tfailseparamagment_notee-ed[-tipeeparm/noteeparm/notee_noteepy-py-peeparamed][-noteepar_noteepyeepy-peeparam][-noteed][-noteepar_notee-noteepy-pee_noteepy-peepy-peeparam][-noteepy-peeparam][-noteepy-peeparam][-noteed][-noteeparamed][-noteepy-peepy-py-peepy-peepy
+
此命令的其他選項如下：

+
[-force][-noprompel]

+
|===


| 如果您想要... | 然後... 


 a| 
*變更目標資料庫主機名稱*
 a| 
指定-hostnew_db_host

|===
. 若要檢視設定檔的目標資料庫主機名稱、請輸入下列命令：SMO profile show

