---
permalink: windows/task_configuring_e_mail_notification_for_a_new_profile.html 
sidebar: sidebar 
keywords: creating, new, profile, configure, email, notification, completion, database, operation, configuring 
summary: 建立新設定檔時、您可以設定在資料庫作業完成時接收電子郵件通知。 
---
= 設定新設定檔的電子郵件通知
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
建立新設定檔時、您可以設定在資料庫作業完成時接收電子郵件通知。

* 您必須設定傳送警示的電子郵件地址。
* 您必須針對多個電子郵件地址使用以逗號分隔的清單。
+
您必須確保在逗號和下一個電子郵件地址之間沒有空格。

+

NOTE: 您必須確保在雙引號內輸入一組電子郵件地址。

+
.. 輸入下列命令：mos profile create -profileprofile [-profile-password-countprofile_password]-reposite-dbnamerepo_service_name-hovernpo_host-portrepo_log-usernamerepo_username-database-dbnamedb_dbnamedb_hostdb_host [-siddb_siddb_sid_sid][-login-tfill-usernamedamed[-puredam_deparam_deparamed][-noteepam_depamed[-noteepam_deeparam_deepamedamed][-noteeparamedamedam_deepam_deepam_depamed[-noteepam_depamed][-noteepamed[-noteepam_deepamed[-noteeparamedamed][-noteepamed[-peeparamedamed][-noteepam_depamed[-noteepam_depamed][-pass
+
此命令的其他選項如下：

+
[力]

+

NOTE: 支援最多1000個字元的電子郵件地址。SnapManager

+
當您使用設定檔（建立個別的歸檔記錄備份）一起建立資料檔案和歸檔記錄檔備份、而且資料檔案備份建立失敗時、電子郵件通知會以作業名稱的形式傳送資料備份、而非以資料備份和歸檔記錄備份的形式傳送。當資料檔案和歸檔記錄檔備份作業成功時、您會看到下列輸出：

+
[listing]
----

Profile Name    : PROF_31
Operation Name 	: Data Backup and Archive Logs Backup
Database SID   	: TENDB1
Database Host 	 : repo1.rtp.org.com
Start Date 	    : Fri Sep 23 13:37:21 EDT 2011
End Date 	      : Fri Sep 23 13:45:24 EDT 2011
Status 	        : SUCCESS
Error messages 	:
----



