---
permalink: unix-administration/concept_what_database_restore_is.html 
sidebar: sidebar 
keywords: snapmanager, enable, perform, volume-based, file-based, restore, opertion, 
summary: 利用支援功能、您可以執行磁碟區型或檔案型的備份與還原作業。SnapManager 
---
= 什麼是資料庫還原
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
利用支援功能、您可以執行磁碟區型或檔案型的備份與還原作業。SnapManager

下表說明還原方法：

|===
| 還原程序 | 詳細資料 


 a| 
Volume型快速還原（從主要儲存設備）
 a| 
還原完整Volume、還原資料庫的資料檔案。SnapManager此預設程序是還原資料庫的最快方法。



 a| 
檔案型還原
 a| 
儲存端完整檔案系統還原（從主要或次要）：SnapManager 執行完整的邏輯單元編號（LUN）還原。



 a| 
儲存端檔案還原：SnapManager 在NAS環境中執行單一檔案快照還原（SFSR）、或在自動儲存管理（ASM）環境中執行部分檔案快照還原（PFSR）。在SFSR中、代表受保護物件的檔案或LUN會還原。如果檔案系統詳細資料和檔案系統配置自上次備份後仍未變更、則會從本機備份執行PFSR。
 a| 
主機端檔案複本還原（從主要或次要）：SnapManager 使用LUN或FlexClone來複製本機備份。複本隨即掛載SnapManager 、然後將主機檔案從實體複本複製到作用中的檔案系統。

|===
雖然預設為快速還原程序、但系統管理員可以選擇任一類型。在快速還原程序中SnapManager 、提供資訊、說明無法完成快速還原程序的情況、以及可能影響快速還原的情況、但如果系統管理員選擇繼續執行此程序、則可以忽略這些情況。


NOTE: 如果主要儲存設備上也存在備份、則無法從次要儲存設備還原備份。

完成快速還原作業後SnapManager 、即可執行下列工作：

* 將較新的備份（在備份還原後進行）釋放到同一個設定檔中、因為其Snapshot複本不再存在於主要儲存設備上。
* 刪除所有Snapshot複本、以便在快速還原程序自動刪除任何Snapshot複本的同一個設定檔中進行備份。
+
如此可避免部分釋放備份。例如、會先建立備份A、然後建立備份B。每個都有資料檔案的Snapshot複本、以及歸檔記錄的Snapshot複本。使用快速還原程序還原備份A之後SnapManager 、NetApp會自動從Backup B刪除資料檔案Snapshot複本SnapManager由於在快速還原程序中未還原歸檔記錄、SnapManager 因此在快速還原程序完成後、必須刪除備份B的歸檔記錄Snapshot複本。





== 快速還原

快速還原或磁碟區型還原的名稱如此之高、因為它是最快的還原方法。整個儲存系統磁碟區會還原為Snapshot複本。在儲存層級、此還原幾乎是即時的。不過、執行Volume還原可能會產生下列負面影響、因此必須謹慎使用：

* 整個儲存端磁碟區會還原、包括下列項目：
+
** 未被視為備份一部分的檔案
** 磁碟區上的其他檔案、檔案系統或LUN


* 在將磁碟區還原至的Snapshot複本之後所建立的所有Snapshot複本都會刪除。
+
例如、如果磁碟區已還原星期一的備份、則無法再還原星期二的備份。

* 如果還原的Snapshot複本早於關聯中的基準Snapshot複本、則與二線儲存系統的關係將會中斷。




== 儲存端完整檔案系統還原

當無法執行Volume還原時、會執行儲存端的完整檔案系統還原、但整個檔案系統可以在儲存系統上還原。

執行儲存端檔案系統還原時、會發生下列情況：

* 在SAN環境中、檔案系統使用的所有LUN（以及基礎Volume群組（如果有）都會還原至儲存系統。
* 在NAS環境中、檔案系統中的每個檔案都會在儲存系統上還原。
+
對於NAS環境、此還原機制並不提供儲存設備端檔案還原的額外效益。



執行儲存端檔案系統還原時、視儲存位置而定、會發生下列情況：

* 從主要儲存系統還原時、LUN（SAN）或檔案（NAS）會透過SFSR還原到位。SnapManager
* 從二線儲存系統還原時、LUN（SAN）或檔案（NAS）會透過網路從二線儲存系統複製回一線儲存系統。SnapManager


由於檔案系統已完全還原、因此也會還原不屬於備份的檔案。如果還原的檔案系統中存在不屬於還原部分的檔案、則需要覆寫。



== 儲存端檔案還原

有時候、當無法執行儲存端檔案系統還原時、就會執行儲存端檔案還原。在儲存設備端檔案還原中、檔案系統內的個別檔案會直接還原至儲存系統。

此類還原只能在NFS環境中執行。

對於ASM環境、只有在符合下列條件時、才能執行儲存端檔案還原：

* 自進行備份以來、基礎檔案範圍並未變更（例如、檔案未調整大小、磁碟也未重新平衡）。
* 您正在從主要儲存系統進行還原。（從二線儲存系統還原時不支援此功能。）


執行儲存端檔案還原時、會發生下列情況：

* 當從主要儲存系統還原NFS檔案時SnapManager 、會使用SFSR就地還原個別檔案。
* 當從二線儲存系統還原NFS檔案時SnapManager 、個別檔案會透過儲存網路複製回一線儲存系統。
* 從主要儲存系統還原ASM檔案時、只要還原與要還原之檔案相關的基礎LUN位元組（LUN中的其餘位元組仍保持不變）、即可就地還原個別檔案。用於部分還原LUN的儲存系統技術稱為PFSR。




== 主機端檔案還原

當無法執行快速還原、儲存端檔案系統還原及儲存端檔案還原時、主機端的檔案複本還原將作為SAN環境中的最後一種方法。

主機端檔案複本還原涉及下列工作：

* 複製儲存設備
* 將複製的儲存設備連接至主機
* 將檔案從複製檔案系統複製回作用中檔案系統
* 中斷實體複本儲存設備與主機的連線
* 刪除複製儲存設備


從二線儲存設備還原時SnapManager 、首先會嘗試將資料直接從二線儲存系統還原至一線儲存系統（不涉及主機）。如果SnapManager 無法執行此類型的還原（例如、如果檔案系統中存在不屬於還原部分的檔案）、SnapManager 則將執行主機端的檔案複製還原。下列兩種方法可從二線儲存設備執行主機端檔案複本還原。SnapManager將在SMo.config檔案中設定此方法。SnapManager

* 直接：SnapManager 將資料複製到二線儲存設備、將複製的資料從二線儲存系統掛載到主機、然後將資料從複本複製到使用中環境。這是預設的次要存取原則。
* 間接：SnapManager 首先將資料複製到主要儲存設備的暫用磁碟區、然後將資料從暫用磁碟區掛載到主機、再將資料從暫用磁碟區複製到作用中環境。僅當主機無法直接存取次要儲存系統時、才應使用此次要存取原則。使用此方法進行還原所需時間是直接次要存取原則的兩倍、因為會建立兩份資料複本。


決定是否使用直接或間接方法、是由SMo.config組態檔中restore.secondaryAccessPolicy參數的值所控制。預設為Direct。
