---
permalink: unix-administration/reference_the_smosmsapclone_create_command.html 
sidebar: sidebar 
keywords: run, clone, create, command, backed-up, database, primary, secondary, storage 
summary: 您可以執行Clone create命令、建立備份資料庫的複本。您可以從一線或二線儲存設備複製備份。 
---
= 使用「建立複本」命令
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以執行Clone create命令、建立備份資料庫的複本。您可以從一線或二線儲存設備複製備份。



== 語法

[listing]
----

        smo clone create
-profile profile_name
[-backup-id backup_guid \| -backup-label backup_label_name \| -current\]
-newsid new_sid
\[-host target_host\]
[-label clone_label]
\[-comment string\]
-clonespec full_path_to_clonespec_file
\[-asminstance -asmusername asminstance_username  -asmpassword asminstance_password\]]
\[-syspassword syspassword\]
\[-reserve \{yes \| no \| inherit\}\]
\[-from-secondary \{-copy-id id\}\]
\[-no-resetlogs \| -recover-from-location path1 \[, path2\]\]\[-taskspec taskspec\]
\[-dump\]
\[-quiet \| -verbose\]
----


== 參數

* *設定檔名稱*
+
指定要複製的資料庫。設定檔包含資料庫和其他資料庫資訊的識別碼。

* *備份ID guid*
+
使用指定的GUID複製備份。當SnapManager 您建立備份時、會產生由支援所產生的GUID。您可以使用SMO備份list-verbose命令來顯示每個備份的Guid。

* *備份標籤backup_label_name*
+
指定使用指定的標籤名稱來複製備份。

* *目前*
+
指定從資料庫的目前狀態建立備份與複製。

+

NOTE: 如果資料庫處於nocarchivelog模式、SnapManager 則會建立離線備份。

* -newsid new_sid*
+
為複製的資料庫指定新的唯一Oracle系統識別碼。系統識別碼值最多八個字元。Oracle不允許在同一主機上同時執行兩個具有相同系統識別碼的資料庫。

* *主機target主機*
+
指定應在其上建立實體複本的主機。

* *標籤clone_label*
+
指定實體複本的標籤。

* *註釋字串*
+
指定可選的註釋來描述此克隆。您必須將字串括在單引號內。

+

NOTE: 有些Shell會刪除引號。如果您的Shell確實如此、則必須使用反斜槓（\）來轉義報價。例如、您可能需要輸入：「這是註解」。

* -clonespec Full_path_to_clonespec_file*
+
指定複製規格XML檔案的路徑。這可以是相對路徑名稱或絕對路徑名稱。

* *：asminstance *
+
指定用於登入ASM執行個體的認證資料。

* -asmusername asminstation_username*
+
指定用於登入ASM執行個體的使用者名稱。

* -asmpassword asminstation_password*
+
指定用於登入ASM執行個體的密碼。

* -syspassWord syspassword*
+
指定sys授權使用者的密碼。

+

NOTE: 如果系統權限使用者所提供的資料庫認證資料不同、您必須提供系統權限使用者的密碼。

* *保留*
+
將-Reserve選項設為yes、可確保新複製磁碟區的磁碟區保證空間保留功能已開啟。將-Reserve選項設為no、可確保新複製磁碟區的磁碟區保證空間保留功能已關閉。將-Reserve選項設為Inheriting、可確保新的實體複本繼承父Snapshot複本的空間保留特性。預設設定為「否」

+
下表說明複製方法及其對複製建立作業及其保留選項的影響。LUN可以使用任一方法複製。

+
|===


| 複製方法 | 說明 | 結果 


 a| 
 LUN cloning a| 
 A new clone LUN is created within the same volume. a| 
 When the -reserve option for a LUN is set to yes, space is reserved for the full LUN size within the volume.


 a| 
 Volume cloning a| 
 A new FlexClone is created, and the clone LUN exists within the new clone volume. Uses the FlexClone technology. a| 
 When the -reserve option for a volume is set to yes, space is reserved for the full volume size within the aggregate.
+

|===
* 來源-次要[-Copy-idCopy_id]*
+
指定SnapManager 應將受保護的備份複本複製到二線儲存設備。如果未指定此選項、SnapManager 則由主儲存設備複製複本。

+
只要指定-from輔助選項、就必須指定-copy（複製）ID選項。如果二線儲存系統上有多個備份、則可使用-COPy-id選項來指定次要儲存設備上的備份複本應用於複製。

+

NOTE: 如果您使用Data ONTAP 的是以7-Mode運作的功能、則必須為-copy -id選項指定有效值。不過、如果您使用叢集Data ONTAP 式的功能、則不需要複製ID選項。

* *無重新設置記錄*
+
指定在建立複本時跳過還原資料庫、執行DBNEWID公用程式、而不使用重新設定記錄開啟資料庫。

* *：從位置恢復*
+
指定歸檔記錄備份的外部歸檔記錄檔位置SnapManager 、其中的資訊為從外部位置取得歸檔記錄檔、並使用它們進行複製。

* 工作規格*
+
指定工作規格XML檔案、用於複製作業的預先處理活動或後處理活動。您必須提供工作規格XML檔案的完整路徑。

* *傾印*
+
指定在複製建立作業之後收集傾印檔案。

* *-無聲*
+
僅在主控台顯示錯誤訊息。預設設定為顯示錯誤和警告訊息。

* *-詳細*
+
在主控台顯示錯誤、警告和資訊訊息。





== 範例

下列範例使用針對此複本所建立的複本規格來複製備份：

[listing]
----
smo clone create -profile SALES1 -backup-label full_backup_sales_May -newsid
CLONE -label sales1_clone -clonespec /opt/<path>/smo/clonespecs/sales1_clonespec.xml
----
[listing]
----
Operation Id [8abc01ec0e794e3f010e794e6e9b0001] succeeded.
----
*相關資訊*

xref:task_creating_clone_specifications.adoc[建立複製規格]

xref:task_cloning_databases_from_backups.adoc[從備份複製資料庫]
