---
permalink: unix-administration/reference_the_smosmsap_clone_split_command.html 
sidebar: sidebar 
keywords: clone, split, command, independent, original, snapmanager 
summary: 您可以執行Clone分割命令來分割實體複本。分割實體複本會獨立於原始實體複本。在複製分割作業之後、會產生一個新的設定檔、您可以使用此設定檔來管理分割複本。SnapManager 
---
= 使用SMO Clone分割命令
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以執行Clone分割命令來分割實體複本。分割實體複本會獨立於原始實體複本。在複製分割作業之後、會產生一個新的設定檔、您可以使用此設定檔來管理分割複本。SnapManager



== 語法

[listing]
----

        smo clone split
-profile clone-profile
\[-host hostname\]
\{-label clone-label | -id clone-id\} \[-split-label split-operation_label\]
\[-comment comment\]
-new-profile new-profile-name \[-profile-password new-profile_password\]
-repository -dbname repo_service_name
-host repo_host
-port repo_port
-login -username repo_username
-database -dbname db_dbname
-host db_host \[-sid db_sid\] \[-login -username db_username -password db_password
-port db_port\]
\[-rman \{\{-controlfile \| \{-login -username rman_username
-password rman_password\} -tnsname rman_tnsname\}\}\]
-osaccount osaccount
-osgroup osgroup
\[-retain
\[-hourly \[-count n\] \[-duration  m\]\]
\[-daily \[-count n\] \[-duration m\]\]
\[-weekly  \[-count n\] \[-duration m\]\]
\[-monthly \[-count n\] \[-duration m\]\] \]
\[-profile-comment profile-comment\]
\[-snapname-pattern pattern\]
\[-protect \[-protection-policy policy_name\]\] \| \[-noprotect\]\]
\[-summary-notification
\[-notification
\[-success -email email_address1,email_address2
-subject subject-pattern\]
\[failure -email email_address1,email_address2
-subject subject-pattern\] \]
[-separate-archivelog-backups
-retain-archivelog-backups
 -hours  hours |
-days days |
-weeks weeks |
-months months
[-protect \[-protection-policy policy_name \| -noprotect]
[-include-with-online-backups \| -no-include-with-online-backups]]
[-dump]
\[-quiet \| -verbose\]
----


== 參數

* *設定檔複製設定檔*
+
指定建立複本的設定檔名稱。

* *主機名稱*
+
指定實體複本所在的主機名稱。

* *標籤實體複製標籤*
+
指定複製作業所產生的標籤名稱。

* -id clone：id*
+
指定複製作業所產生的唯一ID。

* *分割標籤分割作業標籤*
+
指定複製作業所產生的標籤名稱。

* 新設定檔new-profile_name*
+
指定SnapManager 成功分割作業後、將產生的新設定檔名稱。

* -profile密碼new-profile密碼*
+
指定設定檔的密碼。

* *儲存庫*
+
指定儲存庫資料庫的詳細資料。

* *-dbname repo_service_name*
+
指定儲存庫的資料庫名稱。您可以使用全域名稱或系統識別碼。

* *主機repo_host*
+
指定儲存庫資料庫所在主機電腦的名稱或IP位址。

* *連接埠repo_port*
+
指定用於存取儲存庫資料庫所在主機的傳輸控制傳輸協定（TCP）連接埠號碼。

* *登入*
+
指定儲存庫登入詳細資料。這是選用的。如果未指定SnapManager 、則無法使用作業系統驗證連線模式。

* *使用者名稱repo_username*
+
指定存取儲存庫資料庫所在主機所需的使用者名稱。

* *資料庫*
+
指定要備份、還原或複製的資料庫詳細資料。

* *-dbname db_dbname*
+
指定設定檔所描述的資料庫名稱。您可以使用全域名稱或系統識別碼。

* *主機db_host*
+
指定資料庫所在主機電腦的名稱或IP位址。

* -SID db_SID*
+
指定設定檔所描述之資料庫的系統識別碼。根據預設SnapManager 、系統識別碼會使用資料庫名稱。如果系統識別碼與資料庫名稱不同、您必須使用-sID選項來指定。

+
例如、如果您使用Oracle Real Application叢集（RAC）、則必須在RAC節點上指定RAC執行個體的系統識別碼、SnapManager 以執行執行此功能。

* *登入*
+
指定資料庫登入詳細資料。

* *使用者名稱db_username*
+
指定存取設定檔所描述之資料庫所需的使用者名稱。

* *密碼db_password*
+
指定存取設定檔所描述之資料庫所需的密碼。

* *-RMAN *
+
指定SnapManager 使用Oracle Recovery Manager（RMAN）來分類備份的詳細資料。

* *控制檔*
+
將目標資料庫控制檔指定為RMAN儲存庫、而非目錄。

* *登入*
+
指定RMAN登入詳細資料。

* *密碼RMAN密碼*
+
指定用於登入RMAN目錄的密碼。

* *使用者名稱RMAN_USERNAME*
+
指定用於登入RMAN目錄的使用者名稱。

* -tnssname tnssname*
+
指定tnsname連線名稱（定義於tssname.ora檔案）。

* * osAccount osaccount*
+
指定Oracle資料庫使用者帳戶的名稱。支援此帳戶執行Oracle作業、例如啟動和關機。SnapManager通常是擁有主機上Oracle軟體的使用者、例如Oracle。

* * osgroup osgroup *
+
指定與Oracle帳戶相關聯的Oracle資料庫群組名稱。

+

NOTE: UNIX需要-osAccount和-osgroup變數、但Windows上執行的資料庫則不允許。

* *保留[-每小時[-計數n][-持續時間m][-每日[-計數n][-持續時間m]][-每週[-計數n][-持續時間m]]][-每月[-計數n][-持續時間m]]]*
+
指定備份的保留原則。

+
對於每個保留類別、可能會指定保留數或保留期間。持續時間以課程單位為單位（例如小時、日）。例如、如果您只指定每日備份的保留時間為7、SnapManager 則不會限制設定檔的每日備份次數（因為保留次數為0）、SnapManager 但會自動刪除7天前建立的每日備份。

* *設定檔註解設定檔註解*
+
指定描述設定檔網域的設定檔註解。

* *快照名稱模式*
+
指定Snapshot複本的命名模式。您也可以在所有Snapshot複本名稱中加入自訂文字、例如用於高可用度作業的HAOPS。您可以在建立設定檔或建立設定檔之後、變更Snapshot複本命名模式。更新的模式僅適用於尚未建立的Snapshot複本。現有的Snapshot複本會保留先前的Snapname模式。您可以在模式文字中使用多個變數。

* *保護-保護-原則policy_name*
+
指定是否應將備份保護至次要儲存設備。

+

NOTE: 如果指定-protection時沒有-protection原則、則資料集將不會有保護原則。如果指定了-protection且在建立設定檔時未設定-protection-policy、則稍後可透過SMO設定檔更新命令加以設定、或是由儲存管理員使用Protection Manager的主控台加以設定。

* *摘要通知*
+
指定在儲存庫資料庫下為多個設定檔設定摘要電子郵件通知的詳細資料。系統會產生這封電子郵件。SnapManager

* *通知*
+
指定設定新設定檔電子郵件通知的詳細資料。系統會產生這封電子郵件。SnapManager此電子郵件通知可讓資料庫管理員接收電子郵件、告知使用此設定檔執行的資料庫作業狀態為「成功」或「失敗」。

* *成功*
+
指定SnapManager 當執行完此動作時、會針對設定檔啟用電子郵件通知。

* *電子郵件地址1電子郵件地址2 *
+
指定收件者的電子郵件地址。

* 主題模式*
+
指定電子郵件主旨。

* *故障*
+
指定SnapManager 當功能無法運作時、會針對設定檔啟用電子郵件通知。

* *獨立的歸檔儲存設備備份*
+
指定歸檔記錄備份與資料檔案備份分開。這是選用參數、可在建立設定檔時提供。使用此選項分隔備份之後、您可以建立純資料檔備份或僅歸檔記錄備份。

* *保留歸檔日誌備份-小時數|-日天數|-週數週|-月數*
+
指定根據歸檔記錄保留期間（每小時、每日、每週或每月）來保留歸檔記錄備份。

* *保護[-protection、policyypolicy_name]|-nosprote*
+
指定根據歸檔記錄保護原則來保護歸檔記錄檔。

+
指定使用-noprotProtect選項不會保護歸檔記錄檔。

* 包括線上備份|-no include-with online備份*
+
指定在線上資料庫備份時隨附歸檔記錄備份。

+
指定不會隨線上資料庫備份一起提供歸檔記錄備份。

* *傾印*
+
指定在成功建立設定檔之後、不會收集傾印檔案。

* *-無聲*
+
僅在主控台顯示錯誤訊息。預設設定會顯示錯誤和警告訊息。

* *-詳細*
+
在主控台顯示錯誤、警告和資訊訊息。


