---
permalink: unix-administration/task_mounting_backups.html 
sidebar: sidebar 
keywords: snapmanager, automatic, handle, mount, backup, available, host, scenario, rman, 7-mode 
summary: 自動處理備份的安裝、以便主機使用。SnapManager您也可以在使用外部工具（例如Oracle Recovery Manager \（RMAN））存取備份檔案的情況下、掛載備份。 
---
= 掛載備份
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
自動處理備份的安裝、以便主機使用。SnapManager您也可以在使用外部工具（例如Oracle Recovery Manager（RMAN））存取備份檔案的情況下、掛載備份。

如果您使用RMAN、則必須使用掛載作業來變更備份狀態（允許存取）、以及卸載作業來變更備份狀態（移除存取）。

此時、可使用SMO備份掛載命令顯示已掛載Snapshot複本（包含備份）的路徑清單。

您可以使用-from次要選項、從次要儲存設備掛載備份。如果您不使用此選項、SnapManager 則由主儲存設備安裝此備份。

只要指定-from輔助選項、就必須指定-copy（複製）ID選項。如果二線儲存系統上有多個備份、則可使用-COPy-id選項來指定次要儲存設備上的備份複本應用於掛載備份。6.


NOTE: 如果您使用Data ONTAP 的是以7-Mode運作的功能、則必須為-copy -id選項指定有效值。不過、如果您使用叢集Data ONTAP 式的功能、則不需要複製ID選項。

如果您要將資料庫備份掛載到遠端主機、則必須確保兩個主機上的自動儲存管理（ASM）認證資訊相同。


NOTE: 您可以選擇在備份掛載作業成功或失敗之後收集傾印檔案。

. 若要掛載備份、請輸入下列命令：「mo備用掛載-profile profile_name｛labelLabel [data |-archivelogs]|-idid｝[-host-host][-four-secondary [-copy -id id]][-dump][-quid|-verbose]」


*相關資訊*

xref:reference_the_smosmsapbackup_mount_command.adoc[使用SMO備份掛載命令]
