---
permalink: unix-administration/task_updating_target_database_hostname_associated_with_a_profile.html 
sidebar: sidebar 
keywords: snapmanager, 3.2, oracle, provide, ability, update, host, name, target, database, snapmanager, profile, smo 
summary: 適用於Oracle的零件（3.2或更新版本）可在「Isetprofile」（英文）設定檔中更新目標資料庫的主機名稱。SnapManager SnapManager 
---
= 更新與設定檔相關聯的目標資料庫主機名稱
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
適用於Oracle的零組件（3.2或更新版本）可在支援的功能中更新目標資料庫的主機名稱。SnapManager SnapManager

* 本機使用者的主目錄必須知道設定檔對儲存庫的對應。
* 必須關閉圖形化使用者介面（GUI）工作階段。SnapManager
* 在真實應用程式叢集（RAC）環境中、必須刪除及卸載設定檔中指定主機上可用的複本或掛載備份。


您只能使用CLI、以新的主機名稱更新設定檔。

*不支援在設定檔*中變更目標資料庫主機名稱的情況

下列情況不支援變更設定檔中的目標資料庫主機名稱：

* 使用SnapManager Isname GUI變更目標資料庫主機名稱
* 更新設定檔的目標資料庫主機名稱後、將儲存庫資料庫復原
* 執行單一命令來更新新目標資料庫主機名稱的多個設定檔
* 執行SnapManager 任何功能不全的作業時、請變更目標資料庫主機名稱
* 如果SnapManager 在Solaris上安裝了支援程序、而且資料庫邏輯單元編號（LUN）是使用裝有SVM堆疊的主機掛載檔案系統來建立、請變更目標資料庫主機名稱。



NOTE: 在設定檔中更新目標資料庫主機名稱之後、只會變更目標資料庫主機名稱。設定檔上設定的所有其他組態參數都會保留。

在啟用保護的設定檔中更新新的目標資料庫主機名稱之後、更新的設定檔會保留相同的資料集和保護原則。

變更目標主機的主機名稱之後、您必須確保在建立新的受保護設定檔之前、先更新所有現有受保護設定檔的主機名稱。若要更新設定檔的主機名稱、請執行「SMO設定檔更新」命令。

更新目標資料庫主機名稱之後、如果新主機中沒有可用的實體複本或掛載備份、則無法刪除或分割實體複本或卸載備份。在這種情況SnapManager 下、從新主機執行支援功能會導致故障、以及舊主機中的過時項目。若要執行SnapManager 還原作業、您必須使用設定檔更新來還原至較早的主機名稱。

. 輸入下列命令： 「mo profile update -profileprofile [-profile-password-profile_password][-database-dbnamedb_dbname-hostdb_host [-siddb_sid][-login-usernamedb_username-pasedb_passworddb_password_port][{-rMAN problemed] usepyour-past-noteeparm/noteed][-pyour-preme-noteed] notee-notee-noteepyour][-preme-noteed][-preme-noteep-noteed][-topyour] noteeparm/noteepyour][-prem] notee-notee-notee-notee-notee-notee-noteep][-prem][-py-prem][-py-py-py-prem] noteed][-preme-notee-noteed] noteed][-preme-notee-notee-notee-noteep][-py-py-py-py-py-py-preme-not
+
此命令的其他選項如下：

+
[-force][-noprompel]

+
|===


| 如果您想要... | 然後... 


 a| 
*變更目標資料庫主機名稱*
 a| 
指定-hostnew_db_host

|===
. 若要檢視設定檔的目標資料庫主機名稱、請輸入下列命令：「mo profile show」

